"""
gen_keys.py - Mint deterministic key material for a ZEROAUDIT deployment.

    python -m scripts.gen_keys > .env

Writes the three secrets the prover needs to keep a stable identity across
restarts:

  ZEROAUDIT_MASTER_KEY  HMAC key for deriving per-transaction blinding factors
  LWE_SEED_HEX          seed for the Module-LWE public matrix and secret
  SGX_SIGNING_KEY_B64   Ed25519 seed for signing published commitments

Without them each boot mints fresh keys: previously published commitments
become unopenable and every prior signature stops verifying.

These are real secrets. Do not commit the resulting .env - it is gitignored.
"""

import os
import base64


def main():
    print("# ZEROAUDIT key material - generated by scripts/gen_keys.py")
    print("# Secret. Never commit this file.")
    print()
    print("ZEROAUDIT_MASTER_KEY=%s" % os.urandom(32).hex())
    print("LWE_SEED_HEX=%s" % os.urandom(32).hex())
    print("SGX_SIGNING_KEY_B64=%s" % base64.b64encode(os.urandom(32)).decode())


if __name__ == "__main__":
    main()
